//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.GoodsComment = new HashSet<GoodsComment>();
            this.GoodsImage = new HashSet<GoodsImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<int> GoodsColorId { get; set; }
        public Nullable<int> GoodsSizeId { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Saled { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> OnSale { get; set; }
    
        public virtual GoodsColor GoodsColor { get; set; }
        public virtual GoodsSize GoodsSize { get; set; }
        public virtual GoodsType GoodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsComment> GoodsComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsImage> GoodsImage { get; set; }
    }
}
